### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by KirtiJha** [aheber/tree-sitter-sfapex#31]
Hi,
I am trying to install tree-sitter-sfapex, but I am getting error with node-gyp-rebuild. Here is the complete log,
```
npm install tree-sitter-sfapex --verbose
npm verbose cli /Users/kirtijha/.nvm/versions/node/v20.17.0/bin/node /Users/kirtijha/.nvm/versions/node/v20.17.0/bin/npm
npm info using npm@10.8.2
npm info using node@v20.17.0
npm verbose title npm install tree-sitter-sfapex
npm verbose argv "install" "tree-sitter-sfapex" "--loglevel" "verbose"
npm verbose logfile logs-max:10 dir:/Users/kirtijha/.npm/_logs/2024-08-27T12_28_22_203Z-
npm verbose logfile /Users/kirtijha/.npm/_logs/2024-08-27T12_28_22_203Z-debug-0.log
npm verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
npm http fetch GET 200 https://registry.npmjs.org/tree-sitter-sfapex 1238ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/tree-sitter 97ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/node-addon-api 66ms (cache revalidated)
npm info run tree-sitter-sfapex@1.0.3 install node_modules/tree-sitter-sfapex node-gyp-build
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 292ms
npm http fetch GET 200 https://registry.npmjs.org/ssh2 67ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/git-node-platform 119ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/git-node 79ms (cache revalidated)
npm info run tree-sitter-sfapex@1.0.3 install { code: 1, signal: null }
npm verbose stack Error: command failed
npm verbose stack     at promiseSpawn (/Users/kirtijha/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:22:22)
npm verbose stack     at spawnWithShell (/Users/kirtijha/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:124:10)
npm verbose stack     at promiseSpawn (/Users/kirtijha/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:12:12)
npm verbose stack     at runScriptPkg (/Users/kirtijha/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:77:13)
npm verbose stack     at runScript (/Users/kirtijha/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script.js:9:12)
npm verbose stack     at /Users/kirtijha/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/rebuild.js:329:17
npm verbose stack     at run (/Users/kirtijha/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:67:22)
npm verbose stack     at /Users/kirtijha/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:84:9
npm verbose stack     at new Promise (<anonymous>)
npm verbose stack     at callLimit (/Users/kirtijha/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:35:69)
npm verbose pkgid tree-sitter-sfapex@1.0.3
npm error code 1
npm error path /Users/kirtijha/Documents/WatsonX Projects/AI-PE/create-vectordb-nodejs/node_modules/tree-sitter-sfapex
npm error command failed
npm error command sh -c node-gyp-build
npm error touch Release/obj.target/node_modules/node-addon-api/node_addon_api_except.stamp
npm error   cc -o Release/obj.target/tree_sitter_sfapex_binding/apex/src/parser.o ../apex/src/parser.c '-DNODE_GYP_MODULE_NAME=tree_sitter_sfapex_binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DNAPI_CPP_EXCEPTIONS' '-DBUILDING_NODE_EXTENSION' -I/Users/kirtijha/Library/Caches/node-gyp/20.17.0/include/node -I/Users/kirtijha/Library/Caches/node-gyp/20.17.0/src -I/Users/kirtijha/Library/Caches/node-gyp/20.17.0/deps/openssl/config -I/Users/kirtijha/Library/Caches/node-gyp/20.17.0/deps/openssl/openssl/include -I/Users/kirtijha/Library/Caches/node-gyp/20.17.0/deps/uv/include -I/Users/kirtijha/Library/Caches/node-gyp/20.17.0/deps/zlib -I/Users/kirtijha/Library/Caches/node-gyp/20.17.0/deps/v8/include -I../apex/src -I../node_modules/node-addon-api  -O3 -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/tree_sitter_sfapex_binding/apex/src/parser.o.d.raw   -c
npm error   cc -o Release/obj.target/tree_sitter_sfapex_binding/soql/src/parser.o ../soql/src/parser.c '-DNODE_GYP_MODULE_NAME=tree_sitter_sfapex_binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DNAPI_CPP_EXCEPTIONS' '-DBUILDING_NODE_EXTENSION' -I/Users/kirtijha/Library/Caches/node-gyp/20.17.0/include/node -I/Users/kirtijha/Library/Caches/node-gyp/20.17.0/src -I/Users/kirtijha/Library/Caches/node-gyp/20.17.0/deps/openssl/config -I/Users/kirtijha/Library/Caches/node-gyp/20.17.0/deps/openssl/openssl/include -I/Users/kirtijha/Library/Caches/node-gyp/20.17.0/deps/uv/include -I/Users/kirtijha/Library/Caches/node-gyp/20.17.0/deps/zlib -I/Users/kirtijha/Library/Caches/node-gyp/20.17.0/deps/v8/include -I../apex/src -I../node_modules/node-addon-api  -O3 -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/tree_sitter_sfapex_binding/soql/src/parser.o.d.raw   -c
npm error   cc -o Release/obj.target/tree_sitter_sfapex_binding/sosl/src/parser.o ../sosl/src/parser.c '-DNODE_GYP_MODULE_NAME=tree_sitter_sfapex_binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DNAPI_CPP_EXCEPTIONS' '-DBUILDING_NODE_EXTENSION' -I/Users/kirtijha/Library/Caches/node-gyp/20.17.0/include/node -I/Users/kirtijha/Library/Caches/node-gyp/20.17.0/src -I/Users/kirtijha/Library/Caches/node-gyp/20.17.0/deps/openssl/config -I/Users/kirtijha/Library/Caches/node-gyp/20.17.0/deps/openssl/openssl/include -I/Users/kirtijha/Library/Caches/node-gyp/20.17.0/deps/uv/include -I/Users/kirtijha/Library/Caches/node-gyp/20.17.0/deps/zlib -I/Users/kirtijha/Library/Caches/node-gyp/20.17.0/deps/v8/include -I../apex/src -I../node_modules/node-addon-api  -O3 -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/tree_sitter_sfapex_binding/sosl/src/parser.o.d.raw   -c
npm error   c++ -bundle -undefined dynamic_lookup -Wl,-search_paths_first -mmacosx-version-min=10.7 -arch x86_64 -L./Release -stdlib=libc++  -o Release/tree_sitter_sfapex_binding.node Release/obj.target/tree_sitter_sfapex_binding/apex/src/parser.o Release/obj.target/tree_sitter_sfapex_binding/soql/src/parser.o Release/obj.target/tree_sitter_sfapex_binding/sosl/src/parser.o Release/obj.target/tree_sitter_sfapex_binding/bindings/node/binding.o
npm error /Users/kirtijha/Documents/WatsonX Projects/AI-PE/create-vectordb-nodejs/node_modules/node-gyp-build/node-gyp-build.js:60
npm error   throw new Error('No native build was found for ' + target + '\n    loaded from: ' + dir + '\n')
npm error   ^
npm error
npm error Error: No native build was found for platform=darwin arch=x64 runtime=node abi=115 uv=1 libc=glibc node=20.17.0
npm error     loaded from: /Users/kirtijha/Documents/WatsonX Projects/AI-PE/create-vectordb-nodejs/node_modules/tree-sitter-sfapex
npm error
npm error     at load.resolve.load.path (/Users/kirtijha/Documents/WatsonX Projects/AI-PE/create-vectordb-nodejs/node_modules/node-gyp-build/node-gyp-build.js:60:9)
npm error     at load (/Users/kirtijha/Documents/WatsonX Projects/AI-PE/create-vectordb-nodejs/node_modules/node-gyp-build/node-gyp-build.js:22:30)
npm error     at Object.<anonymous> (/Users/kirtijha/Documents/WatsonX Projects/AI-PE/create-vectordb-nodejs/node_modules/node-gyp-build/build-test.js:19:19)
npm error     at Module._compile (node:internal/modules/cjs/loader:1469:14)
npm error     at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
npm error     at Module.load (node:internal/modules/cjs/loader:1288:32)
npm error     at Module._load (node:internal/modules/cjs/loader:1104:12)
npm error     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
npm error     at node:internal/main/run_main_module:28:49
npm error
npm error Node.js v20.17.0
npm error
npm error gyp info it worked if it ends with ok
npm error gyp verb cli [
npm error gyp verb cli '/Users/kirtijha/.nvm/versions/node/v20.17.0/bin/node',
npm error gyp verb cli '/Users/kirtijha/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
npm error gyp verb cli 'rebuild'
npm error gyp verb cli ]
npm error gyp info using node-gyp@10.1.0
npm error gyp info using node@20.17.0 | darwin | x64
npm error gyp verb clean removing "build" directory
npm error gyp verb find Python checking Python explicitly set from command line or npm configuration
npm error gyp verb find Python - "--python=" or "npm config get python" is "python3"
npm error gyp verb find Python - executing "python3" to get executable path
npm error gyp verb find Python - executable path is "/usr/local/bin/python3"
npm error gyp verb find Python - executing "/usr/local/bin/python3" to get version
npm error gyp verb find Python - version is "3.10.8"
npm error gyp info find Python using Python version 3.10.8 found at "/usr/local/bin/python3"
npm error gyp verb get node dir no --target version specified, falling back to host node version: 20.17.0
npm error gyp verb install input version string "20.17.0"
npm error gyp verb install installing version: 20.17.0
npm error gyp verb install --ensure was passed, so won't reinstall if already installed
npm error gyp verb install version is already installed, need to check "installVersion"
npm error gyp verb got "installVersion" 11
npm error gyp verb needs "installVersion" 11
npm error gyp verb install version is good
npm error gyp verb get node dir target node version installed: 20.17.0
npm error gyp verb build dir attempting to create "build" dir: /Users/kirtijha/Documents/WatsonX Projects/AI-PE/create-vectordb-nodejs/node_modules/tree-sitter-sfapex/build
npm error gyp verb build dir "build" dir needed to be created? Yes
npm error gyp verb build/config.gypi creating config file
npm error gyp verb build/config.gypi writing out config file: /Users/kirtijha/Documents/WatsonX Projects/AI-PE/create-vectordb-nodejs/node_modules/tree-sitter-sfapex/build/config.gypi
npm error gyp verb config.gypi checking for gypi file: /Users/kirtijha/Documents/WatsonX Projects/AI-PE/create-vectordb-nodejs/node_modules/tree-sitter-sfapex/config.gypi
npm error gyp verb common.gypi checking for gypi file: /Users/kirtijha/Documents/WatsonX Projects/AI-PE/create-vectordb-nodejs/node_modules/tree-sitter-sfapex/common.gypi
npm error gyp verb gyp gyp format was not specified; forcing "make"
npm error gyp info spawn /usr/local/bin/python3
npm error gyp info spawn args [
npm error gyp info spawn args '/Users/kirtijha/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm error gyp info spawn args 'binding.gyp',
npm error gyp info spawn args '-f',
npm error gyp info spawn args 'make',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/Users/kirtijha/Documents/WatsonX Projects/AI-PE/create-vectordb-nodejs/node_modules/tree-sitter-sfapex/build/config.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/Users/kirtijha/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/Users/kirtijha/Library/Caches/node-gyp/20.17.0/include/node/common.gypi',
npm error gyp info spawn args '-Dlibrary=shared_library',
npm error gyp info spawn args '-Dvisibility=default',
npm error gyp info spawn args '-Dnode_root_dir=/Users/kirtijha/Library/Caches/node-gyp/20.17.0',
npm error gyp info spawn args '-Dnode_gyp_dir=/Users/kirtijha/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/node-gyp',
npm error gyp info spawn args '-Dnode_lib_file=/Users/kirtijha/Library/Caches/node-gyp/20.17.0/<(target_arch)/node.lib',
npm error gyp info spawn args '-Dmodule_root_dir=/Users/kirtijha/Documents/WatsonX Projects/AI-PE/create-vectordb-nodejs/node_modules/tree-sitter-sfapex',
npm error gyp info spawn args '-Dnode_engine=v8',
npm error gyp info spawn args '--depth=.',
npm error gyp info spawn args '--no-parallel',
npm error gyp info spawn args '--generator-output',
npm error gyp info spawn args 'build',
npm error gyp info spawn args '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error gyp verb build type Release
npm error gyp verb architecture x64
npm error gyp verb node dev dir /Users/kirtijha/Library/Caches/node-gyp/20.17.0
npm error gyp verb python /usr/local/bin/python3
npm error gyp verb `which` succeeded for `make` /usr/bin/make
npm error gyp verb bin symlinks created symlink to "/usr/local/bin/python3" in "/Users/kirtijha/Documents/WatsonX Projects/AI-PE/create-vectordb-nodejs/node_modules/tree-sitter-sfapex/build/node_gyp_bins" and added to PATH
npm error gyp info spawn make
npm error gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
npm error clang: error: no such file or directory: 'Release/obj.target/tree_sitter_sfapex_binding/bindings/node/binding.o'
npm error make: *** [Release/tree_sitter_sfapex_binding.node] Error 1
npm error gyp ERR! build error 
npm error gyp ERR! stack Error: `make` failed with exit code: 2
npm error gyp ERR! stack at ChildProcess.<anonymous> (/Users/kirtijha/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:209:23)
npm error gyp ERR! System Darwin 23.5.0
npm error gyp ERR! command "/Users/kirtijha/.nvm/versions/node/v20.17.0/bin/node" "/Users/kirtijha/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm error gyp ERR! cwd /Users/kirtijha/Documents/WatsonX Projects/AI-PE/create-vectordb-nodejs/node_modules/tree-sitter-sfapex
npm error gyp ERR! node -v v20.17.0
npm error gyp ERR! node-gyp -v v10.1.0
npm error gyp ERR! not ok
npm verbose cwd /Users/kirtijha/Documents/WatsonX Projects/AI-PE/create-vectordb-nodejs
npm verbose os Darwin 23.5.0
npm verbose node v20.17.0
npm verbose npm  v10.8.2
npm verbose exit 1
npm verbose code 1
```
I am very new to this. Any help with this is very much appreciated. We are trying to use this to build something very important for our project. Thank You!

**Comment by xixiaofinland** [comment]
https://chatgpt.com/share/428f1030-e461-4e73-b79f-c5b7ab4d0475

To be honest, "very new", "very much appreciated", "very important" these words together leave a bad taste in my mouth.

**Comment by aheber** [comment]
@KirtiJha I made a mistake in 1.0.3 that incorrectly named the Intel version of the compiled binary. 1.0.4 should have that corrected if you want to give it a try. I also wasn't including one of the files needed to rebuild it locally if a native binary wasn't pre-built.

Please let me know if that resolves the direct installation problem.

If you can share, I'd love to hear what you're using the library for. I like hearing about applications of this project.

**Comment by KirtiJha** [comment]
@aheber I will give 1.0.4 a try and let you know. I am building a RAG based code assistance for salesforce that can generate apex and lwc codes by taking existing code and metadata as context. It can also answer questions related to different classes, lwc and other salesforce metadata. 

I am trying to use this library to chunk the existing code by parsing the tree and create embeddings.

**Comment by aheber** [comment]
Sounds like a cool project. Please let me know when you have something publicly available.
